language: php

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - docker

before_script:
  - composer self-update
  - composer install
  - composer docker-build
  - composer docker-run
  - sleep 5

script:
 - ./vendor/bin/codecept run --env nochecking --env knownhosts --env strictchecking --coverage-xml

after_script:
  - ./vendor/bin/coveralls
